### ISSUE TITLE
Console quit from FAbot is hairy

### ISSUE THREAD

**Issue by mdennehy** [darkChozo/FAbot#13]
Ctrl-C from the console should trigger a clean exit from FAbot; right now, it generates a keyboardinterrupt but doesn't exit and you have to killall Python to get out. This needs fixing before it goes up on a 24/7 server.

**Comment by darkChozo** [comment]
I forget where I saw this but I'm pretty sure this is a discord.py issue.

**Comment by Boberro** [comment]
Traceback (most recent call last):
  File "/Users/boberro/Dev/FAbot/fa_bot.py", line 366, in <module>
    client.run()
  File "/Users/boberro/Dev/FAbot/.venv/lib/python2.7/site-packages/discord/client.py", line 525, in run
    self.ws.run()
  File "/Users/boberro/Dev/FAbot/.venv/lib/python2.7/site-packages/ws4py/websocket.py", line 427, in run
    if not self.once():
  File "/Users/boberro/Dev/FAbot/.venv/lib/python2.7/site-packages/ws4py/websocket.py", line 300, in once
    b = self.sock.recv(self.reading_buffer_size)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 241, in recv
    return self.read(buflen)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 160, in read
    return self._sslobj.read(len)
KeyboardInterrupt

**Comment by Boberro** [comment]
Oh my god, I think I have it - event manager waits till next event, and creates a thread that does the waiting.
That is it waits till sunday/tuesday before it closes the application.

**Comment by mdennehy** [comment]
Fixed.
